version: '3.7'

services:
  main:
    container_name: users-avatar-api
    build: .
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    env_file:
      - .env
    networks:
      - webnetwork
    depends_on:
      - postgres
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  postgres:
    container_name: postgresss
    image: postgres:12
    # ports:
    #   - 5433:5432
    networks:
      - webnetwork
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgvolume:/var/lib/postgresql/data

networks:
  webnetwork:
volumes:
  pgvolume:
